WebAPICore/Controllers/KendoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
//using AutoMapper;
using BO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCCallAPICore.Models;
using WebAPI.Models;
using Civica.Core.BO;
using Microsoft.AspNetCore.Authorization;
using APIRequestsCore.WebRequestInterface;


namespace MVCCallAPICore.Controllers
{
    public class KendoController : Controller
    {
        private readonly IEmployeeService _employeeService;
        List<LoadData> treeData = new List<LoadData>();
        public KendoController(IEmployeeService employeeService)
        {
            _employeeService = employeeService;

        }
        public async Task<IActionResult> Employee()
        {
            List<Employee> employees=new List<Employee>();
            //employees = await _employeeService.GetEmployee().ConfigureAwait(false);
            return PartialView("~/Views/Kendo/Events.cshtml", employees);
        }

        public IActionResult Slider()
        {
            return View();
        }
        public JsonResult GetEmployees()
        {
            //List<Employee> employees;
            //employees = _employeeService.GetEmployee().Result;

            //return Json(employees);

            treeData.Add(new LoadData
            {
                Id = 1,
                Parent = 0,
                Text = "Item 1",
                Expanded = true,
                NodeProperty = new Dictionary<string, string>() {
                    { "class", "text-blue" },
                    { "value", "Item 1" }
                    }
            });
            treeData.Add(new LoadData
            {
                Id = 2,
                Parent = 0,
                Text = "Item 2",
                LinkProperty = new Dictionary<string, string>() {
                    { "class", "text-underline" },
                    { "href", "http://www.syncfusion.com" },
                    { "target", "_blank"}
                    }
            });
            treeData.Add(new LoadData
            {
                Id = 3,
                Parent = 0,
                Text = "Item 3",
                Selected = true,
                SpriteImage = "mailicon sprite-calendar"
            });
            treeData.Add(new LoadData
            {
                Id = 4,
                Parent = 0,
                Text = "Item 4",
                NodeChecked = true,
                ImageProperty = new Dictionary<string, string>() {
                    { "width", "20px" },
                    { "height", "20px" }
                    },
                ImageURL = "http://cdn.syncfusion.com/13.3.0.7/js/web/flat-azure/images/ajax-loader.gif"
            });
            treeData.Add(new LoadData
            {
                Id = 5,
                Parent = 1,
                Text = "Item 1.1"
            });
            treeData.Add(new LoadData
            {
                Id = 6,
                Parent = 1,
                Text = "Item 1.2"
            });
            treeData.Add(new LoadData
            {
                Id = 7,
                Parent = 1,
                Text = "Item 1.3"
            });
            treeData.Add(new LoadData
            {
                Id = 8,
                Parent = 3,
                Text = "Item 3.1"
            });
            treeData.Add(new LoadData
            {
                Id = 9,
                Parent = 3,
                Text = "Item 3.2"
            });
            treeData.Add(new LoadData
            {
                Id = 10,
                Parent = 5,
                Text = "Item 1.1.1"
            });
            //ViewBag.datasource = treeData;
            //return View();
            //return Json(treeData, JsonRequestBehavior.AllowGet);
            return Json(treeData);
        }
        public ActionResult TreeView()
        {
            List<Employee> employees = new List<Employee>();
            //employees = await _employeeService.GetEmployee().ConfigureAwait(false);
            return PartialView("~/Views/Kendo/Grid.cshtml", employees);

           
        }
    }
}

WebAPICore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCallAPICore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.bootstrap-v4.min.css" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2020.2.617/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2020.2.617/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2020.2.617/js/kendo.aspnetmvc.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCCallAPICore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kendo" asp-action="Slider">Kendo Slider</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="UploadFile">Upload File</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CreateDropDown">Drop Down</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CreatePeople">Create People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Slider">Slider</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Users">Users</a>
                        </li>
                       

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MVCCallAPICore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>